### ISSUE TITLE
Error: Cannot find module 'turbo'

### ISSUE THREAD

**Issue by jlarmstrongiv** [vercel/turborepo#1126]
### What version of Turborepo are you using?

1.2.5

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

I have a project named `turbo-monorepo`, with `"turbo": "^1.2.5",` specified in the `devDependencies`.  Running `npx turbo` should use my project installation of turborepo.  However, it errors with:

```
npm run turbo:build:all

> turbo-monorepo@1.0.0 turbo:build:all
> npx turbo run turbo:build --force

/workspaces/turbo-monorepo/node_modules/turbo/bin/turbo:13
    throw e;
    ^

Error: Cannot find module 'turbo'
Require stack:
- /workspaces/turbo-monorepo/node_modules/turbo/node-platform.js
- /workspaces/turbo-monorepo/node_modules/turbo/bin/turbo
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at downloadedBinPath (/workspaces/turbo-monorepo/node_modules/turbo/node-platform.js:56:44)
    at generateBinPath (/workspaces/turbo-monorepo/node_modules/turbo/node-platform.js:79:15)
    at Object.<anonymous> (/workspaces/turbo-monorepo/node_modules/turbo/bin/turbo:7:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/turbo-monorepo/node_modules/turbo/node-platform.js',
    '/workspaces/turbo-monorepo/node_modules/turbo/bin/turbo'
  ]
}
```

I am just using the stand vscode Dockerfile:

```Dockerfile
ARG VARIANT="14"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}-buster
RUN su node -c "npm install --global npm"
```

### Expected Behavior

`npx turbo` works regardless of whether turborepo is installed in the global scope or project scope.

### To Reproduce

Install `turbo` in your dev dependencies, rather than globally.  This is a [common](https://codeburst.io/maybe-dont-globally-install-that-node-js-package-f1ea20f94a00) [pattern](https://expressflow.com/blog/posts/npx-difference-npm-no-global-dependencies) to keep projects self-contained.

**Comment by jlarmstrongiv** [comment]
Ugh, turns out `turbo-linux-64` was missing.

**Comment by jlarmstrongiv** [comment]
@uriklar `turbo-linux-64` is platform specific, so for mac it would be `turbo-darwin-64`

**Comment by jlarmstrongiv** [comment]
For the whole list, check your `node_modules/turbo/package.json` for `optionalDependencies`:

```json
{
  "optionalDependencies": {
    "turbo-android-arm64": "1.3.1",
    "turbo-darwin-64": "1.3.1",
    "turbo-darwin-arm64": "1.3.1",
    "turbo-freebsd-64": "1.3.1",
    "turbo-freebsd-arm64": "1.3.1",
    "turbo-linux-32": "1.3.1",
    "turbo-linux-64": "1.3.1",
    "turbo-linux-arm": "1.3.1",
    "turbo-linux-arm64": "1.3.1",
    "turbo-linux-mips64le": "1.3.1",
    "turbo-linux-ppc64le": "1.3.1",
    "turbo-windows-32": "1.3.1",
    "turbo-windows-64": "1.3.1",
    "turbo-windows-arm64": "1.3.1"
  }
}
```

**Comment by uriklar** [comment]
Thanks! Wanted to update that I was on node 14 and switching to node 16 fixed it.
