### ISSUE TITLE
Turbo crashes when using --remote-only

### ISSUE THREAD

**Issue by runeh** [vercel/turborepo#1167]
### What version of Turborepo are you using?

1.2.6

### What package manager are you using / does the bug impact?

npm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When calling `turbo run` with the `--remote-only` flag, but without the other required remote flags, turbo crashes.

On my box, I get this:

```
 ➜  basic git:(main) yarn build --remote-only
yarn run v1.22.17
$ turbo run build --remote-only
• Packages in scope: config, docs, tsconfig, ui, web
• Running build in 5 packages
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x101092f70]

goroutine 1011 [running]:
github.com/vercel/turborepo/cli/internal/cache.(*asyncCache).Fetch(0x101211060?, {0x1400002a214?, 0x14000515815?}, {0x140005158b0?, 0x0?}, {0x0?, 0x14000490000?, 0x1011efea0?})
	github.com/vercel/turborepo/cli/internal/cache/async_cache.go:54 +0x30
github.com/vercel/turborepo/cli/internal/run.(*execContext).exec(0x140001b53e0, 0x1400055b100, 0x14000572c90?)
	github.com/vercel/turborepo/cli/internal/run/run.go:885 +0x724
github.com/vercel/turborepo/cli/internal/run.(*RunCommand).executeTasks.func1(0x1400055b100)
	github.com/vercel/turborepo/cli/internal/run/run.go:672 +0x74
github.com/vercel/turborepo/cli/internal/run.(*completeGraph).getPackageTaskVisitor.func1({0x14000515810, 0xa})
	github.com/vercel/turborepo/cli/internal/run/run.go:1135 +0x340
github.com/vercel/turborepo/cli/internal/core.(*Scheduler).Execute.func1({0x1011efea0, 0x140005721d0})
	github.com/vercel/turborepo/cli/internal/core/scheduler.go:92 +0xb8
github.com/pyr-sh/dag.(*Walker).walkVertex(0x140001b5440, {0x1011efea0, 0x140005721d0}, 0x14000429d40)
	github.com/pyr-sh/dag@v1.0.0/walk.go:377 +0x2ec
created by github.com/pyr-sh/dag.(*Walker).Update
	github.com/pyr-sh/dag@v1.0.0/walk.go:300 +0xc00
error Command failed with exit code 2.
```

### Expected Behavior

Turbo exits properly, complaining about missing options.

### To Reproduce

In the `examples/basic` folder in the turborepo repo, do this:

```sh
yarn
yarn build --remote-only
```

**Comment by runeh** [comment]
Thanks!
