### ISSUE TITLE
Cannot run create-turbo (inquirer ScreenManager crash)

### ISSUE THREAD

**Issue by fwal** [vercel/turborepo#1222]
### What version of Turborepo are you using?

1.2.8

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

Running `npx create-turbo@latest` results in an error:

```sh
$ npx create-turbo@latest
npx: installed 186 in 19.429s

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.


Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: this.breakLines(...).flat is not a function
    at ScreenManager.forceLineReturn (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/utils/screen-manager.js:172:56)
    at ScreenManager.render (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/utils/screen-manager.js:81:20)
    at InputPrompt.render (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/prompts/input.js:67:17)
    at InputPrompt._run (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/prompts/input.js:34:10)
    at Promise (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/prompts/base.js:61:12)
    at new Promise (<anonymous>)
    at InputPrompt.run (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/prompts/base.js:60:12)
    at defer (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/inquirer/lib/ui/prompt.js:105:30)
    at Observable._subscribe (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/Users/frederik/.npm/_npx/49048/lib/node_modules/create-turbo/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
```

### Expected Behavior

Expected the command to setup turborepo.

### To Reproduce

Running on
- MacBook Pro (M1, 14 inch, 2021)
- macOS 12.3.1
- iTerm 3.4.15
- Fish 3.3.1

Execute command `npx create-turbo@latest`

**Comment by jaredpalmer** [comment]
What version of node.js do you have installed? I'm not able to reproduce

**Comment by lodmfjord** [comment]
This happens in Node 10 and earlier; which is normal since flat is not supported by Node 10.

**Comment by jaredpalmer** [comment]
`create-turbo` works with Node.js 12+
