### ISSUE TITLE
Project dependency is lot loading

### ISSUE THREAD

**Issue by leidsoncruz** [vercel/turborepo#1733]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I installed the `react-dom` in our UI project to use the `ReactDOM.createPortal`. Our next application is using this component that needs the react-dom, but when we access our page, we get this error:

```
Error: Cannot find module '/app/apps/myApp/node_modules/react-dom/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:364:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:577:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.6405 (/app/apps/myApp/.next/server/pages/_document.js:162:18)
    at __webpack_require__ (/app/apps/myApp/.next/server/webpack-runtime.js:25:42)
    at Object.907 (/app/apps/myApp/.next/server/chunks/225.js:1316:27) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/apps/myApp/node_modules/react-dom/package.json',
  requestPath: 'react-dom'
}
Error: Cannot find module '/app/apps/myApp/node_modules/react-dom/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:364:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:577:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.6405 (/app/apps/myApp/.next/server/pages/_document.js:162:18)
    at __webpack_require__ (/app/apps/myApp/.next/server/webpack-runtime.js:25:42)
    at Object.907 (/app/apps/myApp/.next/server/chunks/225.js:1316:27) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/apps/myApp/node_modules/react-dom/package.json',
  requestPath: 'react-dom'
}
```

We are using `require('next-transpile-modules')(['uikit']);` to transpile our module. In theory, we don't use `ReactDOM` directly in the myApp.

I tried to move the `ReactDOM.createPortal` to our next application and install the react-dom there, but I got the same error.

However, when I install the `react-dom` in the root, the application works fine.

ps: Everything works fine when I run in development mode. This error occurs to run next start (prod mode)

### Expected Behavior

The application works without the need to install the `react-dom` into the root.

### To Reproduce

1. Install the dependency in the uikit e.g: react-dom.
2. In the next app, import the component
3. Next app build
4. yarn workspace myApp start

**Comment by tknickman** [comment]
Hey @leidsoncruz this looks to be an issue with the workspace setup, not turborepo (your reproduction steps don't include turbo at all). If you have a reproduction with turbo, we would be glad to take a look, but I'm going to close for now.
