### ISSUE TITLE
`npx create-turbo@latest` fails

### ISSUE THREAD

**Issue by raulmabe** [vercel/turborepo#1856]
### What version of Turborepo are you using?

1.4.5

### What package manager are you using / does the bug impact?

npm, Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When running `npx create-turbo@latest folder-name` it throws the following error:

```sh
➜  Documents npx create-turbo@latest raulmabe
npx: instaló 182 en 11.325s

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Which package manager do you want to use? npm

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/raulmateobeneyto/.npm/_npx/679/lib/node_modules/create-turbo/dist/index.js:319:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)


A new version of `create-turbo` is available!
You can update by running: yarn global add create-turbo

➜  Documents create-turbo --version
zsh: command not found: create-turbo
➜  Documents yarn global add create-turbo
yarn global v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-turbo@1.4.5" with binaries:
      - create-turbo
✨  Done in 7.46s.
➜  Documents create-turbo raulmabe

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Which package manager do you want to use? yarn

Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: import_fs.default.cpSync is not a function
    at run (/Users/raulmateobeneyto/.config/yarn/global/node_modules/create-turbo/dist/index.js:319:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)


A new version of `create-turbo` is available!
You can update by running: yarn global add create-turbo
```

### Expected Behavior

`npx create-turbo@latest` to work out of the box...

### To Reproduce

Just run the command.

`yarn version: 1.22.11`
`npm version: 6.14.15`

**Comment by mattpocock** [comment]
The fix is to upgrade to Node 16.

**Comment by raulmabe** [comment]
If anyone else is having the same issue, I just solved it by upgrading `node` version from `14` to `16`.
