### ISSUE TITLE
Site search breaks with certain inputs?

### ISSUE THREAD

**Issue by qdozaq** [vercel/turborepo#1946]
### What version of Turborepo are you using?

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

So here's an interesting bug.
Not in turbo itself, but `turborepo.org`

Certain inputs into the search bar appear to completely break the site and log the following error:

```
react_devtools_backend.js:4026 TypeError: Cannot read properties of undefined (reading 'split')
    at 648-f5462e4cdb9b304d.js:1:128336
    at oo (framework-b9236ac6f8071c7f.js:1:59412)
    at Wo (framework-b9236ac6f8071c7f.js:1:68979)
    at jo (framework-b9236ac6f8071c7f.js:1:68311)
    at Ku (framework-b9236ac6f8071c7f.js:1:115007)
    at Li (framework-b9236ac6f8071c7f.js:1:98953)
    at Ni (framework-b9236ac6f8071c7f.js:1:98881)
    at Pi (framework-b9236ac6f8071c7f.js:1:98744)
    at bi (framework-b9236ac6f8071c7f.js:1:95710)
    at framework-b9236ac6f8071c7f.js:1:45204
```
![turbo_site_bug](https://user-images.githubusercontent.com/20975817/189981351-d5304ed7-af93-4af7-89e9-a0fc8c527b36.gif)

### Expected Behavior

The search bar should work

### To Reproduce

- Go to any page on `turborepo.org`
- Type the following into the search bar: `pa`

Happens in multiple browsers, on my desktop (macOS), and on my phone(iOS).

**Comment by tknickman** [comment]
Investigating this now

**Comment by tknickman** [comment]
Should be fixed now, thanks for the report @qdozaq!
