### ISSUE TITLE
Weird error messages

### ISSUE THREAD

**Issue by Xenfo** [vercel/turborepo#729]
### What version of Turborepo are you using?

1.1.3-canary.2

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When a run command fails, Turborepo outputs a weird error message.
```
@flux-ui/checkbox:build: src/checkbox.tsx(45,7): error TS2769: No overload matches this call.
@flux-ui/checkbox:build:   Overload 1 of 3, '(props: Omit<CheckboxProps & RefAttributes<HTMLButtonElement>, "checked" | "css" | "as"> & TransformProps<{ checked?: boolean | "false" | undefined; }, {}> & { ...; }): ReactElement<...> | null', gave the following error.
@flux-ui/checkbox:build:     Type 'CheckedState' is not assignable to type 'boolean | "false" | ({ "@initial"?: boolean | "false" | undefined; } & { [x: string]: boolean | "false" | undefined; }) | undefined'.
@flux-ui/checkbox:build:       Type '"indeterminate"' is not assignable to type 'boolean | "false" | ({ "@initial"?: boolean | "false" | undefined; } & { [x: string]: boolean | "false" | undefined; }) | undefined'.
@flux-ui/checkbox:build:   Overload 2 of 3, '(props: Omit<CheckboxProps & RefAttributes<HTMLButtonElement>, "checked" | "css" | "as"> & TransformProps<{ checked?: boolean | "false" | undefined; }, {}> & { ...; }): ReactElement<...> | null', gave the following error.
@flux-ui/checkbox:build:     Type 'CheckedState' is not assignable to type 'boolean | "false" | ({ "@initial"?: boolean | "false" | undefined; } & { [x: string]: boolean | "false" | undefined; }) | undefined'.
@flux-ui/checkbox:build:   Overload 3 of 3, '(props: Omit<CheckboxProps & RefAttributes<HTMLButtonElement>, "checked" | "css"> & TransformProps<{ checked?: boolean | "false" | undefined; }, {}> & { ...; }): ReactElement<...> | null', gave the following error.
@flux-ui/checkbox:build:     Type 'CheckedState' is not assignable to type 'boolean | "false" | ({ "@initial"?: boolean | "false" | undefined; } & { [x: string]: boolean | "false" | undefined; }) | undefined'.
@flux-ui/checkbox:build: 
@flux-ui/checkbox:build: [CHECKBOX] DTS Build error
@flux-ui/checkbox:build: Error: Failed to compile. Check the logs above.
@flux-ui/checkbox:build:     at error (/Users/johnhouse/Documents/flux-ui/node_modules/rollup/dist/shared/rollup.js:160:30)
@flux-ui/checkbox:build:     at throwPluginError (/Users/johnhouse/Documents/flux-ui/node_modules/rollup/dist/shared/rollup.js:21828:12)
@flux-ui/checkbox:build:     at Object.error (/Users/johnhouse/Documents/flux-ui/node_modules/rollup/dist/shared/rollup.js:22548:20)
@flux-ui/checkbox:build:     at Object.error (/Users/johnhouse/Documents/flux-ui/node_modules/rollup/dist/shared/rollup.js:22005:42)
@flux-ui/checkbox:build:     at Object.transform (/Users/johnhouse/Documents/flux-ui/node_modules/tsup/dist/rollup.js:8372:20)
@flux-ui/checkbox:build:     at /Users/johnhouse/Documents/flux-ui/node_modules/rollup/dist/shared/rollup.js:22793:37
@flux-ui/checkbox:build: Error: command finished with error: command (packages/checkbox) yarn yarn run build exited (1)
command (packages/checkbox) yarn yarn run build exited (1)

 Tasks:    1 successful, 2 total
Cached:    0 cached, 2 total
  Time:    4.649s 
```

### Expected Behavior

Expected error message to be `Error: command finished with error: command (packages/checkbox) yarn run build exited (1)` or something like that.

### To Reproduce

Force an error in a run command.

**Comment by jaredpalmer** [comment]
@gsoltis does this have to do with new graceful signal handling?

**Comment by gsoltis** [comment]
Ah, yup. It looks like [`exec.Command`](https://github.com/golang/go/blob/master/src/os/exec/exec.go#L172) prepends the command to be run to the list of arguments, so that when we show the command and its arguments, the command shows up twice. I'll fix up our output.
