### ISSUE TITLE
Vite can't build React app when I include path to ui components in tailwind config

### ISSUE THREAD

**Issue by Aliemeka** [vercel/turborepo#880]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Any time I try to build my application, the build fails

This is what I see in the logs

```
onboard-partner:build: cache miss, executing ee8a3a13576ab8a9
onboard-partner:build: $ vite build
onboard-partner:build: vite v2.8.6 building for production...
onboard-partner:build: transforming...
onboard-partner:build: ✓ 757 modules transformed.
onboard-partner:build: rendering chunks...
onboard-partner:build: [vite:css-post] Transform failed with 4 errors:
onboard-partner:build: <stdin>:700:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:913:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:1231:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:2289:29: ERROR: Unterminated string token
onboard-partner:build: error during build:
onboard-partner:build: Error: Transform failed with 4 errors:
onboard-partner:build: <stdin>:700:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:913:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:1231:29: ERROR: Unterminated string token
onboard-partner:build: <stdin>:2289:29: ERROR: Unterminated string token
onboard-partner:build:     at failureErrorWithLog (/Users/emekaallison/Documents/Projects/Onboard/onboard-frontend/node_modules/esbuild/lib/main.js:1605:15)
onboard-partner:build:     at /Users/emekaallison/Documents/Projects/Onboard/onboard-frontend/node_modules/esbuild/lib/main.js:1394:29
onboard-partner:build:     at /Users/emekaallison/Documents/Projects/Onboard/onboard-frontend/node_modules/esbuild/lib/main.js:668:9
onboard-partner:build:     at handleIncomingPacket (/Users/emekaallison/Documents/Projects/Onboard/onboard-frontend/node_modules/esbuild/lib/main.js:765:9)
onboard-partner:build:     at Socket.readFromStdout (/Users/emekaallison/Documents/Projects/Onboard/onboard-frontend/node_modules/esbuild/lib/main.js:635:7)
onboard-partner:build:     at Socket.emit (node:events:390:28)
onboard-partner:build:     at addChunk (node:internal/streams/readable:315:12)
onboard-partner:build:     at readableAddChunk (node:internal/streams/readable:289:9)
onboard-partner:build:     at Socket.Readable.push (node:internal/streams/readable:228:10)
onboard-partner:build:     at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
onboard-partner:build: [!] Error: unfinished hook action(s) on exit:
onboard-partner:build: (vite:esbuild-transpile) renderChunk
onboard-partner:build: (vite:esbuild-transpile) renderChunk
onboard-partner:build: (vite:esbuild-transpile) renderChunk
onboard-partner:build: (vite:esbuild-transpile) renderChunk
onboard-partner:build: 
onboard-partner:build: error Command failed with exit code 1.
onboard-partner:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
onboard-partner:build: Error: command finished with error: command (apps/onboard-partner) yarn run build exited (1)
```

### Expected Behavior

Expect the build to be successful without any build errors.

### To Reproduce

Create a React App with Vite.js

Add tailwind and the configuration stuff `tailwind.config.js` and `postcss.config.js`

```
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './index.html',
    '../../packages/ui/**/*.{js,jsx,ts,tsx}', // should be include if comment out, it will build but it needs to added
  ],
  darkMode: 'media',
  theme: {
    extend: { },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

**Comment by Aliemeka** [comment]
@jaredpalmer @leerob What do you guys think?

**Comment by jlarmstrongiv** [comment]
@Aliemeka do you have a repository for reproduction?  I’m using tailwindcss with postcss and it works just fine, even when I use something like `"../../libs/**/*.{js,jsx,ts,tsx}"`

**Comment by Aliemeka** [comment]
Oh me get that set up

**Comment by Aliemeka** [comment]
Yeah I get your point @jlarmstrongiv I just made a new turbo project with a react app and I didn't get any issue. Let me check my configurations. 

I haven't been able to fixed the issue on my main project as at yet though

**Comment by Aliemeka** [comment]
Discovered it was an error in my tailwindcss config

**Comment by itschip** [comment]
@Aliemeka mind sharing you fix?
