### ISSUE TITLE
`npx create-turbo@latest -e with-react-native-web` fails installation

### ISSUE THREAD

**Issue by AntoninoGargiuloBID** [vercel/turborepo#9100]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

[CodeSandbox Devbox](https://codesandbox.io/p/devbox/33435q?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0m5d5850006356kv77pumyj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0m5d5850002356ksmylmsfe%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0m5d5850004356kfs6v08rk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0m5d5850005356k9hoet2go%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0m5d5850002356ksmylmsfe%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m5d5850001356k219qcyit%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522cm0m5d5850002356ksmylmsfe%2522%252C%2522activeTabId%2522%253A%2522cm0m5d5850001356k219qcyit%2522%257D%252C%2522cm0m5d5850005356k9hoet2go%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0m5d5850005356k9hoet2go%2522%257D%252C%2522cm0m5d5850004356kfs6v08rk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m5d5850003356kdqeqvttt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cm0m5d6cb000bdgf82x6j3jwv%2522%257D%255D%252C%2522id%2522%253A%2522cm0m5d5850004356kfs6v08rk%2522%252C%2522activeTabId%2522%253A%2522cm0m5d5850003356kdqeqvttt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257Dl)
### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

2.1.1-canary.0

### Describe the Bug

The command `npx create-turbo@latest -e with-react-native-web`, after choosing `npm` as package manager, fails its execution, with the following error message:
```
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: native@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! apps/native/node_modules/react
npm ERR!   react@"^18.2.0" from native@1.0.0
npm ERR!   apps/native
npm ERR!     native@1.0.0
npm ERR!     node_modules/native
npm ERR!       workspace apps\native from the root project
npm ERR!   peer react@"18.2.0" from react-native@0.73.1
npm ERR!   apps/native/node_modules/react-native
npm ERR!     react-native@"0.73.1" from native@1.0.0
npm ERR!     apps/native
npm ERR!       native@1.0.0
npm ERR!       node_modules/native
npm ERR!         workspace apps\native from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native-web@"^0.19.10" from native@1.0.0
npm ERR! apps/native
npm ERR!   native@1.0.0
npm ERR!   node_modules/native
npm ERR!     workspace apps\native from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.3.1
npm ERR! node_modules/react
npm ERR!   peer react@"^18.3.1" from react-dom@18.3.1
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^18.2.0" from native@1.0.0
npm ERR!     apps/native
npm ERR!       native@1.0.0
npm ERR!       node_modules/native
npm ERR!         workspace apps\native from the root project
npm ERR!     peer react-dom@"^18.0.0" from react-native-web@0.19.12
npm ERR!     node_modules/react-native-web
npm ERR!       react-native-web@"^0.19.10" from native@1.0.0
npm ERR!       apps/native
npm ERR!         native@1.0.0
npm ERR!         node_modules/native
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_logs\2024-09-02T15_59_53_699Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_logs\2024-09-02T15_59_53_699Z-debug-0.log        
    at CM (C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:23:57)
    at C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ph (C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:69:2060)
    at async Command.Eg (C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\create-turbo\dist\cli.js:94:7474)
    at async Command.parseAsync (C:\Users\AntoninoGargiulo\AppData\Local\npm-cache\_npx\e8c68b66aeb1424f\node_modules\commander\lib\command.js:936:5) {  
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code ERESOLVE\n' +
    'npm ERR! ERESOLVE could not resolve\n' +
    'npm ERR! \n' +
    'npm ERR! While resolving: native@1.0.0\n' +
    'npm ERR! Found: react@18.2.0\n' +
    'npm ERR! apps/native/node_modules/react\n' +
    'npm ERR!   react@"^18.2.0" from native@1.0.0\n' +
    'npm ERR!   apps/native\n' +
    'npm ERR!     native@1.0.0\n' +
    'npm ERR!     node_modules/native\n' +
    'npm ERR!       workspace apps\\native from the root project\n' +
    'npm ERR!   peer react@"18.2.0" from react-native@0.73.1\n' +
    'npm ERR!   apps/native/node_modules/react-native\n' +
    'npm ERR!     react-native@"0.73.1" from native@1.0.0\n' +
    'npm ERR!     apps/native\n' +
    'npm ERR!       native@1.0.0\n' +
    'npm ERR!       node_modules/native\n' +
    'npm ERR!         workspace apps\\native from the root project\n' +
    'npm ERR! \n' +
    'npm ERR! Could not resolve dependency:\n' +
    'npm ERR! react-native-web@"^0.19.10" from native@1.0.0\n' +
    'npm ERR! apps/native\n' +
    'npm ERR!   native@1.0.0\n' +
    'npm ERR!   node_modules/native\n' +
    'npm ERR!     workspace apps\\native from the root project\n' +
    'npm ERR! \n' +
    'npm ERR! Conflicting peer dependency: react@18.3.1\n' +
    'npm ERR! node_modules/react\n' +
    'npm ERR!   peer react@"^18.3.1" from react-dom@18.3.1\n' +
    'npm ERR!   node_modules/react-dom\n' +
    'npm ERR!     react-dom@"^18.2.0" from native@1.0.0\n' +
    'npm ERR!     apps/native\n' +
    'npm ERR!       native@1.0.0\n' +
    'npm ERR!       node_modules/native\n' +
    'npm ERR!         workspace apps\\native from the root project\n' +
    'npm ERR!     peer react-dom@"^18.0.0" from react-native-web@0.19.12\n' +
    'npm ERR!     node_modules/react-native-web\n' +
    'npm ERR!       react-native-web@"^0.19.10" from native@1.0.0\n' +
    'npm ERR!       apps/native\n' +
    'npm ERR!         native@1.0.0\n' +
    'npm ERR!         node_modules/native\n' +
    'npm ERR! \n' +
    'npm ERR! Fix the upstream dependency conflict, or retry\n' +
    'npm ERR! this command with --force or --legacy-peer-deps\n' +
    'npm ERR! to accept an incorrect (and potentially broken) dependency resolution.\n' +
    'npm ERR! \n' +
    'npm ERR! \n' +
    'npm ERR! For a full report see:\n' +
    'npm ERR! C:\\Users\\AntoninoGargiulo\\AppData\\Local\\npm-cache\\_logs\\2024-09-02T15_59_53_699Z-eresolve-report.txt\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: C:\\Users\\AntoninoGargiulo\\AppData\\Local\\npm-cache\\_logs\\2024-09-02T15_59_53_699Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

The error message says to report this error as bug.

### Expected Behavior

proper installation of all the dependencies, both `web` and `native` projects ready to start.

### To Reproduce

just run the command `npx create-turbo@latest -e with-react-native-web`, and the installation will fail.

**Comment by albertovasquez** [comment]
This issue still persists

**Comment by Shivatack** [comment]
Still

**Comment by unameit10000000** [comment]
Same issue here. Re-installed npm, tried again (npx create-turbo@latest) but it still fails. Yarn works fine.

**Comment by z1haze** [comment]
A workout is to use either --legacy-peer-deps, or --force with npm.

e.g. `NPM_CONFIG_LEGACY_PEER_DEPS=true npx create-turbo@latest --example with-react-native-web .`

**Comment by anthonyshew** [comment]
Hey, everyone. Those of us on the core team has decided to focus on keeping a core subset of the examples found in the repository up to date.

Taking care of **all** of the examples is a *ton* of maintenance work, and we found we're simply not able to spend our time keeping these up to the quality standards we have for ourselves, along with working on `turbo` itself. For that reason, we've decided instead make sure we set the right expectations for community members.

We've marked many of the examples as community-maintained, including this one. You can see [the full lists here](https://turbo.build/repo/docs/getting-started/examples). We won't be accepting Issues for these anymore, and you're highly encouraged to submit PRs for any problems that you find in a community supported example to help out those around you, and we'll be excited to review them with you. Thank you!
