### ISSUE TITLE
The `create-turbo` command fails for yarn package manager with error "Command failed with exit code 1: yarn install"

### ISSUE THREAD

**Issue by trivikr** [vercel/turborepo#9150]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

2.1.2-canary.1

### Describe the Bug

Choosing `yarn` in `create-turbo` fails with exit code 1

```console
$ npx create-turbo@canary -e with-shell-commands 
Need to install the following packages:
create-turbo@2.1.2-canary.1
Ok to proceed? (y) y

? Where would you like to create your Turborepo? test-turborepo-yarn
? Which package manager do you want to use? yarn

>>> Creating a new Turborepo with:

Application packages
 - apps/apps-a: An application that uses other Internal Packages
 - apps/apps-b: A workspace to use as a model for a final application that the rest of your dependencies are building towards.
Library packages
 - packages/pkg-a
 - packages/pkg-b
 - packages/tooling-config: A package used by every other package.

>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: yarn install
warning package.json: No license field
warning my-turborepo: No license field
error Workspaces can only be enabled in private projects.
yarn install v1.22.22
info No lockfile found.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at CM (/Users/trivikr/.npm/_npx/0a7f74da1d0baaa7/node_modules/create-turbo/dist/cli.js:23:57)
    at /Users/trivikr/.npm/_npx/0a7f74da1d0baaa7/node_modules/create-turbo/dist/cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ph (/Users/trivikr/.npm/_npx/0a7f74da1d0baaa7/node_modules/create-turbo/dist/cli.js:69:2060)
    at async Command.Eg (/Users/trivikr/.npm/_npx/0a7f74da1d0baaa7/node_modules/create-turbo/dist/cli.js:94:7474)
    at async Command.parseAsync (/Users/trivikr/.npm/_npx/0a7f74da1d0baaa7/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  escapedCommand: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.22.22\n' +
    'info No lockfile found.\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: 'warning package.json: No license field\n' +
    'warning my-turborepo: No license field\n' +
    'error Workspaces can only be enabled in private projects.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Expected Behavior

The Turborepo project created with yarn package manager

### To Reproduce

Run `npx create-turbo@canary -e with-shell-commands` and choose `yarn`

**Comment by ViniciusLeviVL** [comment]
same issue here

**Comment by chris-olszewski** [comment]
If you add `--skip-install` to the `create-turbo` command and then attempt the `yarn install` inside the repository do you still get an error?

Also, are you expecting a Yarn v1 or a Yarn v3 repository to be created?
