### ISSUE TITLE
Error when building nextjs 15 app while prerendering /500 & /404 (only happens with turborepo)

### ISSUE THREAD

**Issue by ezeamin** [vercel/turborepo#9335]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/ezeamin/turbo-next-15

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

turbo@2.2.4-canary.2

### Describe the Bug

When minimal nextjs app (15.0.1 & 15.0.2-canary.6 - latest up to today) is being built, these errors appear:
```
┌ home#build > cache miss, executing 570f9f11bf8e8c82
│
│ > home@0.0.1 build
│ > next build
│
│   ▲ Next.js 15.0.1
│
│    Creating an optimized production build ...
│  ✓ Compiled successfully
│  ✓ Linting and checking validity of types
│  ✓ Collecting page data
│ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%
│ 20props%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:490)
│     at Xc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:409)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:210)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
│     at $c (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
│     at bd (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:77:404)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:217)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:71:479)
│ Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
│ Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%
│ 20props%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:490)
│     at Xc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:409)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:210)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:481)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
│     at $c (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
│     at bd (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:77:404)
│     at Z (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:217)
│     at Zc (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:71:479)
│ Export encountered an error on /_error: /404, exiting the build.
│  ⨯ Static worker exited with code: 1 and signal: null
│ npm error Lifecycle script `build` failed with error:
│ npm error code 1
│ npm error path C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\apps\home
│ npm error workspace home@0.0.1
│ npm error location C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\apps\home
│ npm error command failed
│ npm error command C:\WINDOWS\system32\cmd.exe /d /s /c next build
│ command finished with error: command (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\apps\home) C:\Program Files\nodejs\npm.cmd run build exited (1)
└────>
home#build: command (C:\Users\Amin\Documents\Codigo\Pruebas\turbo-next-15\apps\home) C:\Program Files\nodejs\npm.cmd run build exited (1)
```

**This may seem a nextjs error, but it doesn't happen outside of a monorepo handled by turborepo.** 

It sometimes shows error while prerendering /404, and sometimes while prerendering /500. This WASN'T happening with nextjs@14. This is shown when "Generating static pages (0/4)" is run, after other stages had finished successfully..

Dev execution runs without problems. Running `npm run build` from `apps/home` also shows the same errors.

It also occurs with bun@1.1.33, tested on linux and windows.

### Expected Behavior

Build finishes without any problems.

### To Reproduce

1. Run `npm i` 
2. Run `npm run build`
3. See console output.

### Additional context

I tested this on different PCs, using next 15,15.0.1, and over canary release 15.0.2-canary.6. Also tested on docker.

**Comment by chris-olszewski** [comment]
I'm confused by the following statements:

> This may seem a nextjs error, but it doesn't happen outside of a monorepo handled by turborepo.

> Running npm run build from apps/home also shows the same errors.

So does the error only appear once `npm add -D turbo` is run in the repository? I removed any `turbo` installation and configuration in the repro you provided and the error remained when I ran `npm run build` from `apps/home`. Could you provide a repro without Turborepo that works as expected?

**Comment by chris-olszewski** [comment]
This is odd, I'm not sure how, but it looks like the `package-lock.json` is in a bad state. I'm able to get a successful build (with and without `turbo`) if I blow it away first:

On a fresh checkout of https://github.com/ezeamin/turbo-next-15/tree/main
```
[0 olszewski@chriss-mbp] /tmp $ gh repo clone ezeamin/turbo-next-15
Cloning into 'turbo-next-15'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 103 (delta 25), reused 103 (delta 25), pack-reused 0 (from 0)
Receiving objects: 100% (103/103), 227.67 KiB | 2.32 MiB/s, done.
Resolving deltas: 100% (25/25), done.
[0 olszewski@chriss-mbp] /tmp $ cd turbo-next-15
[0 olszewski@chriss-mbp] /tmp/turbo-next-15 $ npm i

added 39 packages, and audited 41 packages in 7s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[0 olszewski@chriss-mbp] /tmp/turbo-next-15 $ npm run build

> build
> turbo build

turbo 2.2.4-canary.2

• Packages in scope: home
• Running build in 1 packages
• Remote caching disabled
┌ home#build > cache miss, executing 4e84cf012f59c614 
│ 
│ 
│ > home@0.0.1 build
│ > next build
│ 
│   ▲ Next.js 15.0.2-canary.6
│ 
│    Creating an optimized production build ...
│  ✓ Compiled successfully
│  ✓ Linting and checking validity of types    
│  ✓ Collecting page data    
│  ✓ Generating static pages (4/4)
│  ✓ Collecting build traces    
│  ✓ Finalizing page optimization    
│ 
│ Route (app)                              Size     First Load JS
│ ┌ ○ /                                    139 B          99.8 kB
│ └ ○ /_not-found                          896 B           101 kB
│ + First Load JS shared by all            99.7 kB
│   ├ chunks/765-549bd41c5fd13672.js       45.2 kB
│   ├ chunks/87c73c54-2e1e9fc9dd385a27.js  52.6 kB
│   └ other shared chunks (total)          1.86 kB
│ 
│ 
│ ○  (Static)  prerendered as static content
└────>

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    11.49s
```

I haven't looked into what exactly is incorrect with the lockfile, but it could either be:
 - A lockfile generated from a bad `node_modules` state. (`npm` looks at the current state of `node_modules` on disk for deciding what optional dependencies should be listed in the lockfile, this can cause some to be unintentionally omitted)
 - Something is off with NextJS dependency set that produces a bad lockfile. It could be possible that this only happens in monorepos.

Closing this, as this is outside of Turborepo's control, but if you encounter this again I would encourage you to open an issue in [vercel/next.js](https://github.com/vercel/next.js) along with the exact steps you took to generate the lockfile.

**Comment by chris-olszewski** [comment]
Maybe add a comment on https://github.com/vercel/next.js/issues/71873 which has the same error although it uses `pnpm` it could indicate that there is something up with module resolution when running `next build`/

**Comment by fuzing** [comment]
Also seeing this same problem with turbo 2.3.2 and nextjs 15.0.3 and npm 10.8.2
Have tried everything @GavGrayston mentioned without success.

Build works fine without turborepo (e.g. remove workspaces in root package.json and "fixed" links to dependencies using "file:<path>" instead of "*").

**Comment by GavGrayston** [comment]
- Clean install with ```npx create-turbo@latest```
- ```npx run build``` or ```turbo build``` works
- Add @radix-ui/themes to the UI.  E.g. ```npm install @radix-ui/themes --workspace=web --workspace=@repo/ui```
- Build now fails with the above problem.
- However, this works fine outside of turborepo
- Within the web workspace and UI package, package.json was updated with the radix themes, but not the node_modules.  
But radix-ui was added to the root node modules.  package-lock.json looks correct too.
- Ran ```npm uninstall @radix-ui/themes --workspace=web --workspace=@repo/ui```
- Build still fails with package removed

**Comment by GavGrayston** [comment]
Went back to my original turbo-repo. 

- Deleted all items under `apps`
- Build worked 
- In apps, created a new app using `npx create-next-app@latest'
- Same build error again

**Comment by fuzing** [comment]
@GavGrayston, @ezeamin et. al.......
I found a fix for this for my use case - this may help someone else:  Note that I'm using `npm` for my package manager, so your mileage may differ when using `pnpm`, `yarn` etc.

After performing `npm install` from the root folder, my nextjs application (in the `apps/web-server` sub-folder for me) contained its own `node_modules` folder which only contained `react` and `react-dom` packages.   The root `node_modules` folder also contained the same versions.  For some reason, `next build` seems to be confused by the dueling packages, so I simply deleted my app's `node_modules` folder (i.e. `apps/web-server/node_modules` in my case) and then re-ran the build.   Voila! everything worked fine.

**Comment by GavGrayston** [comment]
Thanks @fuzing! 
I did that, and removed from the sub-app package.json (so they're not put in after `npm install` or `npm update`) and it now builds 👍

**Comment by fuzing** [comment]
@GavGrayston - glad that helped

I took a slightly different approach.  Instead of removing from the sub-app package.json (which is where the dependencies for react/react-dom should really be located),  I created a `clean-react` turbo task which I include as a dependency of the `build` task. There's obviously a corresponding entry in the app's package.json scripts for `clean-react` which does a `rm -rf node_modules/react; rm -rf node_modules/react-dom` (I'm building and deploying for linux so these commands work in that context - should also work on Mac, but not on windows - there's probably an npm file remover package that will work everywhere).

The reason for mentioning this is that pnpm and yarn use different file linking strategies to share packages (and to ensure isolation of dependencies between packages etc.).  Keeping the dependency within the app prevents pollution of the top-level package.json and keeps everything neat and tidy.

**Comment by zhabinsky** [comment]
I am experiencing this issue 1:1

however what worked for you makes no sense to me as I have no duplicate react modules in my sub-app 

```
export const dynamic = "force-dynamic";
```

this worked at the root layout

**Comment by MiltonAkash** [comment]
Same issue.

**Comment by HarjjotSinghh** [comment]
@fuzing That worked for me as well, thanks a lot!

**Comment by mpereira** [comment]
Same issue here. Also in an npm monorepo.

```
    "turbo": "2.3.3"
```

```
    "react": "19.0.0",
    "react-dom": "19.0.0",
```

I found that the root cause is an npm workspace depending on another, with both having `react` and `react-dom` in their `package.json`.

The solution is to make sure that `react` and `react-dom` are only being specified once each, either in the parent or child npm workspace.

Also, is there another issue where this is being discussed? It's surprising that this issue was closed, and the one in the next.js repository referenced in the comments here as well.

Very cryptic and difficult to debug error.

**Comment by fuzing** [comment]
@mpereira - I'd agree that it was surprising that this issue was closed - it's clear that numerous folks are having issues with this.
One thing you mentioned did pique my curiosity....... you talked about parent and child workspaces.  The monorepos I've encountered (and are using/building) haven't had a nested heirarchy of workspaces - I'm wondering if this is officially supported?  Generally, what I see are monorepos with workspaces that are separate from one another (within the same folder structure). Obviously, these workspaces can "depend on" other workspaces, but it's the nesting that is a little curious.
To be clear, for my case, I was talking about a single reference to react and react-dom (in one of my workspaces) - for some reason the react and react-dom dependencies were being created in both the workspace folder plus the root folder, each within the node_modules sub-folder.  This is clearly a bug.

**Comment by inadeqtfuturs** [comment]
just to chime in: using npm and turborepo, i got into this state today, found this thread, and started looking at mis-matched react versions in the child (nextjs app) and parent (root turbo repo) `node_module` folders. i think because i made the transition from next 14 to 15, as well as from react 18 to 19, my root `package-lock.json` still specified and downloaded an older version of react than what the nextjs app needed/wanted.

while i initially got a build to work by deleting my child's `node_modules` as suggested by @fuzing, i ultimately just deleted my root `package-lock.json` and generated a new one. i'm now in a good state.

**Comment by patricklewis** [comment]
I am also being affected by prerendering errors on `/400` and `/500` pages during `turbo run build` in a monorepo managed by Turborepo 2.3.3, trying to upgrade an app from Next.js 14.2 -> 15.1 and React 18.3 -> 19.0

Removing and regenerating `package-lock.json` as mentioned by @inadeqtfuturs above has not fixed the errors in my case.

**Comment by Sljcom** [comment]
> [@GavGrayston](https://github.com/GavGrayston) - glad that helped
> 
> I took a slightly different approach. Instead of removing from the sub-app package.json (which is where the dependencies for react/react-dom should really be located), I created a `clean-react` turbo task which I include as a dependency of the `build` task. There's obviously a corresponding entry in the app's package.json scripts for `clean-react` which does a `rm -rf node_modules/react; rm -rf node_modules/react-dom` (I'm building and deploying for linux so these commands work in that context - should also work on Mac, but not on windows - there's probably an npm file remover package that will work everywhere).
> 
> The reason for mentioning this is that pnpm and yarn use different file linking strategies to share packages (and to ensure isolation of dependencies between packages etc.). Keeping the dependency within the app prevents pollution of the top-level package.json and keeps everything neat and tidy.

Absolutely worked. Thank you!
It does seem NextJS becomes confused due to the monorepo setup and npm packaging structure due to react and react-dom existing in both monorepo/apps/nextjs/node_modules and in monorepo/node_modules.

I created this file, and ran this script by running build from monorepo/apps/nextjs/package.json like so:
`"build": "node ./prepare_build.js && next build",`

Here is prepare_build.js.
`import fs from 'fs';
const nodeModulesPath = './node_modules/';

fs.rmSync(nodeModulesPath + "react", { recursive: true, force: true })
fs.rmSync(nodeModulesPath + "react-dom", { recursive: true, force: true })`

Of course be careful when using rmSync with recursive and force set to true as it obliterates everything in it`s path 🗡

**Comment by Woskus** [comment]
My problem was that in one of my package, I used react & react dom in version 18 but in my next js app I used version 19. Unifying it fixed the problem

**Comment by GoudekettingRM** [comment]
For me what works is what @Woskus also mentions, making sure the react and react dom versions are in line in all apps/packages. I did the following:

`npm i react@latest react-dom@latest next@latest --save --workspace=<app-name>` for all apps

I have one workspace package that uses react as a peer dependency (not react-dom, nor next), so I also updated react there:
`npm i react@latest --save --workspace=packages/ui`

this updated all the react versions in the root level package-lock.json and fixed the issue for me.

**Comment by LeoAnt02** [comment]
This issue is happening also for Nx monorepo (npm workspace)
When your `react` and `react-dom` at package.json mono repo root version are different from `react` and `react-dom` in the package.json in your `app/project`

The temp fix is to delete `react` and `react-dom` in the node_modules in your `app/project` but this is not viable long run

What happens when you have 2 project, and one must be on a specific different react version ? 
like an expo mobile app for example 

we should be allowed to have different version of a package per project 

We need a real fix for this

**Comment by Andrew-Chen-Wang** [comment]
I had to add react and react-dom (and their corresponding `@types/react` to the root package.json in my monorepo. For me, yes it was a type mismatch where the top-level node_modules had React 18 for some reason.

**Comment by JeffBaumgardt** [comment]
I have the fun slight twist where I want multiple versions of react. I have multiple `apps` and some can't be updated to react@19 yet. So I need 18 and 19 to play along. I haven't yet figured out how to get the root `node_modules` to not include react and let the app itself get that since that's where the dependency is.

I've opted to roll the new app 'back' in react to 18, which is not ideal, but the best way forward for me.

Has any had good experience getting multiple apps with varying versions of react going? I would be interested to see how/where dependencies end up.

**Comment by fuzing** [comment]
@limup - your issue is a little confusing because you mention "apps/web-server/node_modules", but the folder tree you display shows something completely different (i.e. a folder called "my-next-project" that contains a single nextjs project, which includes a node_modules folder).

Can you confirm that your project is set up as a monorepo? (and more specifically a monorepo that uses turbo for management).

For a monorepo, which is what this issue/thread is addressing, the behavior you're seeing where you only have a single root level node_modules folder is probably correct - the idea is that the root level node_modules allows sharing of dependencies across any/all sub-packages/projects.  Turbo will (or rather is supposed to) create a node_modules at the sub-project level in cases where there are conflicting versions of packages (e.g. sub project A uses React 18, while sub project B uses React 19).

Monorepos take advantage of the fact that package managers such as npm/pnpm/etc. will first look in the local node_modules folder for a package, and if not found, will recursively walk up to the first parent folder in the file tree looking for a node_modules folder that might contain a matching package:version combination (this process is repeated until a match is found, or the file-system root is reached).

**Comment by vemundeldegard** [comment]
For me, the issue was that I had previously downgraded from React 19 -> 18, and some of my other packages/apps still used 19.  I also forgot to downgrade @types/react and @types/react-dom.

**Comment by ahmedfaaid** [comment]
I had the same issue. I realized that a few of the dependencies in apps/web had older versions of react & react-dom as peer dependencies. My solution was to update them to the versions that have react v19 as a peer dependency and then the error went away.

**Comment by JeromeVH** [comment]
Had the same issue without monorepo, just a simple app which I recently upgraded from next14 and react18 to 15 and 19 respectively, but I had some 'resolutions' still pointing to react 18.
After I cleared these resolutions the build started to work again, wasting couple of days on this :(

**Comment by AtotheY** [comment]
Can't believe there's no official support on this yet - this is such a huge issue, just wasted 3 hours trying to figure out why my nextjs app builds perfectly fine outside of turborepo but gets that misleading error with turborepo.... 🤦‍♂️

**Comment by ErickRoo** [comment]
I have the same problem, i tried to deploy my next.js project from my turborepo and in the build time on vercel appears the errors. In my localhost i just deleted node_modules from my apps/web/(next.js project) to i can build my project but on vercel idk how to do that...

**Comment by kiikoh** [comment]
Still having this issue. And it has been such a time sink, has anyone come across a good solution?

**Comment by kiikoh** [comment]
I got mine to work after deleting node-modules/ like everyone mentioned above. I had a build script `clean` and I trusted it was working but it never actually cleaned anything...

**Comment by zeyaddeeb** [comment]
I spent a couple of hours scratching my head on this. Unifying react versions was the culprit. Thanks for folks who shared.

**Comment by JarvisPrestidge** [comment]
What worked for me in a turborepo monorepo:

```bash
npx npm-check-updates --deep -u // bumping all deps (specifically react/react-rom) to latest
npx npkill // removing all my node_modules

// remove root lockfile
// remove .next folders

npm i // or equivalent
```

I did this all with bun workspaces (replace npm/npx with bun/bunx etc.) and this solved my Next.js build issues...

**Comment by theOneOps** [comment]
So basically, I was working on a monorepo, and then I try to build a project based on nextra with nextjs.

When I get this error, what works for me was :

- To have every repo having its own lock-file, (*basically, remove the package.json file and the lock's file at the root of my monorepo*)
- Then, ***remove .next's folder, and the node_modules***
- And finally ***npm i***

Normally, ***npm run build*** should work

I am using **npm** by the way

**Comment by honnmin** [comment]
In my case, this issue occurs only during production builds (Turbopack SSR workers) — not in next dev — due to how React instances are resolved in monorepo environments.

**Key points:**
- In a Turborepo monorepo, each app (e.g. apps/web, apps/dashboard) and internal UI package (e.g. packages/ui-kit) may depend on slightly different React versions.
- npm hoists one version to the root, but if versions differ, another React copy is installed inside the app’s own node_modules.
- During `next dev`, everything runs in a **_single Node.js process_** with a shared require.cache, so only one React instance is used.
- During `next build`, Turbopack runs **_multiple isolated SSR workers_**, each with its own module cache.
→ Some workers load React from the root, others from the app’s local folder.
→ This leads to multiple React instances in memory and results in useContext(null) or invalid hook call errors.

**Resolution:**
Ensure that all workspaces use the same React and React-DOM versions (e.g. 19.2.0) so that only one instance is ever installed and hoisted.

You can verify this by checking:
```
npm ls react
```

and aligning all mismatched versions across your apps and packages.

**Note:**
Even if the issue seems temporarily resolved after reinstalling, it can reappear when caches are cleared (e.g. when .turbo, .next, or node_modules are deleted and rebuilt).
This happens because hoisting behavior and module resolution may change slightly between installs.

To verify stability or share reproducible results, always remove all caches (node_modules, .next, .turbo) before testing again.
